<?php
require_once __DIR__ . '/_common.php';
require_admin();
$rows = db()->query('SELECT id, code, name, year, pdf_path, quiz_path, updated_at FROM subjects ORDER BY year, code')->fetchAll();
$counts = [1=>0,2=>0,3=>0]; foreach($rows as $r) if(isset($counts[(int)$r['year']])) $counts[(int)$r['year']]++;
$msg = $_GET['msg'] ?? '';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RevSpecs Admin</title><style>
:root{--paper:#fff;--ink:#1B4332;--soft:#5C8374;--line:#CDE8D5;--orange:#E67E22;--green:#27AE60;--red:#C0392B;--r:5px}*{box-sizing:border-box}body{margin:0;background:#f8fbf9;color:var(--ink);font-family:Arial,sans-serif}.wrap{max-width:1050px;margin:auto;padding:30px 20px 70px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid var(--ink);padding-bottom:16px;margin-bottom:20px;gap:15px}h1{margin:0;font-size:2rem}h2{margin:0 0 15px}.muted{color:var(--soft)}.top-actions{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-block;padding:10px 14px;border-radius:var(--r);border:1px solid var(--line);background:#fff;color:var(--ink);text-decoration:none;font-weight:700;font-size:.88rem}.btn.primary{background:var(--orange);border-color:var(--orange);color:#fff}.btn.danger{background:#fff;border-color:#efb5ae;color:var(--red)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:24px}.stat{background:#fff;border:2px solid var(--line);padding:16px;border-top:5px solid var(--green)}.stat:nth-child(1){border-top-color:var(--orange)}.stat:nth-child(3){border-top-color:#D35400}.num{font-size:1.7rem;font-weight:700}.subject-group{background:#fff;border:2px solid var(--line);margin-bottom:18px;border-radius:var(--r);overflow:hidden}.group-title{padding:12px 15px;font-weight:700;background:#f3fbf6}.subject{display:grid;grid-template-columns:1.1fr 1.8fr 70px 70px 190px;gap:14px;align-items:center;padding:14px 15px;border-top:1px solid var(--line)}.subject-code{font-weight:700}.status{font-size:.83rem}.yes{color:var(--green);font-weight:700}.no{color:var(--red);font-weight:700}.actions{display:flex;gap:6px;justify-content:flex-end;flex-wrap:wrap}.actions .btn{padding:7px 9px;font-size:.78rem}.empty{padding:25px;color:var(--soft)}.subject-name-cell .updated{font-size:.72rem;color:var(--soft);margin-top:2px}@media(max-width:750px){.stats{grid-template-columns:1fr}.subject{grid-template-columns:1fr;gap:6px}.actions{justify-content:flex-start}header{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="wrap"><header><div><h1>RevSpecs Admin</h1><div class="muted">Welcome, <?=h($_SESSION['admin_username'] ?? 'admin')?>.</div></div><div class="top-actions"><a class="btn" href="../index.php">View RevSpecs</a><a class="btn danger" href="logout.php">Log out</a></div></header>
<?php if($msg):?><div style="background:#eafaf1;padding:11px;margin-bottom:18px;border:1px solid var(--line)"><?=h($msg)?></div><?php endif;?>
<div class="stats"><div class="stat"><div class="num"><?=$counts[1]?></div><div class="muted">1st year subjects</div></div><div class="stat"><div class="num"><?=$counts[2]?></div><div class="muted">2nd year subjects</div></div><div class="stat"><div class="num"><?=$counts[3]?></div><div class="muted">3rd year subjects</div></div></div>
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h2>Subjects</h2><a class="btn primary" href="subject-edit.php">+ Add subject</a></div>
<?php foreach([1,2,3] as $year): $group=array_filter($rows,fn($r)=>(int)$r['year']===$year);?><section class="subject-group"><div class="group-title"><?=$year?><?=($year===1?'st':($year===2?'nd':'rd'))?> Year</div><?php if(!$group):?><div class="empty">No subjects yet.</div><?php else: foreach($group as $s):?><div class="subject"><div class="subject-code"><?=h($s['code'])?></div><div class="subject-name-cell"><?=h($s['name'])?><?php if($s['updated_at']):?><div class="updated">Updated <?=h(date('M j, Y', strtotime($s['updated_at'])))?></div><?php endif;?></div><div class="status"><?php if($s['pdf_path']):?><span class="yes">✓ PDF</span><?php else:?><span class="no">✗ PDF</span><?php endif;?></div><div class="status"><?php if($s['quiz_path']):?><span class="yes">✓ Quiz</span><?php else:?><span class="no">✗ Quiz</span><?php endif;?></div><div class="actions"><a class="btn" href="subject-edit.php?id=<?=$s['id']?>">Edit</a><?php if($s['pdf_path']):?><a class="btn" href="../<?=h($s['pdf_path'])?>" target="_blank">PDF</a><?php endif;?><?php if($s['quiz_path']):?><a class="btn" href="../<?=h($s['quiz_path'])?>" target="_blank">Quiz</a><?php endif;?><form method="post" action="subject-delete.php" onsubmit="return confirm('Delete this subject, its PDF, and its quiz?');" style="display:inline"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=$s['id']?>"><button class="btn danger" type="submit">Delete</button></form></div></div><?php endforeach; endif;?></section><?php endforeach;?></div></body></html>